
name: 'dataflow360'
version: '1.0.0'
config-version: 2

profile: 'dataflow360'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dataflow360:
    marts:
      +materialized: table
      +schema: curated
